import { Ubuntu } from "next/font/google";
import "./globals.css";
import styles from "./mainLayout.module.css";
import footerData from "../../public/footerData";
import { MdCopyright } from "react-icons/md";
import Link from "next/link";
const ubuntu = Ubuntu({
  weight: "400",
  subsets: ["latin"],
  display: "auto",
});
export const metadata = {
  title: "Tech Shop",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <nav className={styles.nav}>
          <Link className={styles.logoLink} href={"/"}>
            <h2>Tech Store</h2>
          </Link>
          <ul className={styles.navItems}>
            <li className={styles.item}>
              <Link href={"/products"}>Products</Link>
            </li>
          </ul>
        </nav>
        {children}
        <footer className={styles.footer}>
          <div className={styles.footerTop}>
            <h3>{footerData.logo}</h3>
            <ul className={styles.items}>
              {footerData.footerLinks.map((link, idx) => (
                <li key={idx} className={styles.item}>
                  {link}
                </li>
              ))}
            </ul>
          </div>
          <h6 className={styles.copy}>
            <MdCopyright />
            {footerData.copyright}
          </h6>
        </footer>
      </body>
    </html>
  );
}
